apiVersion : apps/v1
kind: Deployment
metadata:
  name: sampleapp 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp 
    spec:
      containers:
        - name: myapp 
          image: project1acrs.azurecr.io/myapp:latest
          ports:
          - containerPort: 80